#!/usr/bin/env perl
use Mojolicious::Lite;
use Digest::MD5 qw(md5_hex);
use Mojo::Redis2;
use Mojo::JSON 'j';

helper redis => sub { shift->stash->{redis} ||= Mojo::Redis2->new; };

get '/' => => sub { shift->redirect_to('code', code => substr(md5_hex(scalar localtime),0,3)) };

get '/:code' => {code => ''} => sub {
  my $c = shift;
  my $code = $c->param('code');
  my $loc = j($c->redis->get($code) || '[]');
  $c->render(code => $code, loc => $loc);
};

post '/:code' => sub {
  my $c = shift;
  my ($code, $geo) = ($c->param('code'), [$c->param('lat'), $c->param('lon')]);
  $c->redis->set($code => j($geo));
  $c->redis->expire($code => 3 * 60);
  $c->render(json => {$code => $geo});
};

app->start;
__DATA__

@@ code.html.ep
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="http://ctrlq.org/common/css/bootstrap.min.css" rel="stylesheet">
    <link href="style.css" rel="stylesheet">
  </head>
  <body>
    <!-- Code: <input name=code value="<%= $code %>" /><div id="code-btn">Submit</div><br /> -->
    <br /><div><a href="/<%= $code %>"><div class="link"><%= $code %></div></a><div class="link"> : </div><a id="map" href="#"><div id="loc" class="link"></div></a></div>
    <div id="googlemaps"></div>

    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDKw1I9ZlI-piCBp2zXSuviBDVRjju-aYI&sensor=true&libraries=adsense"></script>
    <script src="geoposition.js"></script>
    <script src="http://ctrlq.org/common/js/jquery.min.js"></script>
    <script src="http://ctrlq.org/common/js/bootstrap.min.js"></script>
    <script src="http://ctrlq.org/common/js/ga.js"></script>
    <script>
      function locationFound(position) {
      % if ( @$loc ) {
        //showMap(<%= $loc->[0] %>, <%= $loc->[1] %>);
        $('#loc').html(<%= $loc->[0] %> + ', ' + <%= $loc->[1] %>);
        $('#map').attr('href', "https://www.google.com/maps/place//@<%= $loc->[0] %>,<%= $loc->[1] %>,15z/data=!3m1!4b1!4m2!3m1!1s0x0:0x0");
      % } else {
        //showMap(position.coords.latitude, position.coords.longitude);
        $('#loc').html(position.coords.latitude + ', ' + position.coords.longitude);
        $('#map').attr('href', "https://www.google.com/maps/place//@"+position.coords.latitude+","+position.coords.longitude+",15z/data=!3m1!4b1!4m2!3m1!1s0x0:0x0");
	$.post('/<%= $code %>', {lat: position.coords.latitude, lon: position.coords.longitude});
      % }
      }
    </script>
    <script src="functions.js"></script>

  </body>
</html>

@@ style.css
html, body {
  height: 100%; margin: 0; padding: 0;
}
form{margin:0}
.navbar-inner {padding:.5em;border-radius:0;-moz-border-radius:0;}
h1 {font-size:18px;}
h3 {margin-bottom:.5em; }
//#googlemaps { height: 90%; }
#iw {width:260px;font-family:monospace;}
div {padding:.5em;margin:.5em;display:inline;align-vertical:bottom;height:100px}
.link {padding:.5em;margin:.5em;font-size:40px;align-vertical:bottom}
.navbar {margin:0}
img {max-width:none;}
hr {margin:5px 0}

@@ geoposition.js
//
// javascript-mobile-desktop-geolocation
// https://github.com/estebanav/javascript-mobile-desktop-geolocation
//
// Copyright J. Esteban Acosta Villafañe
// Licensed under the MIT licenses.
//
// Based on Stan Wiechers > geo-location-javascript v0.4.8 > http://code.google.com/p/geo-location-javascript/
//
// Revision: $Rev: 01 $: 
// Author: $Author: estebanav $:
// Date: $Date: 2012-09-07 23:03:53 -0300 (Fri, 07 Sep 2012) $:    

var bb = { 
        success: 0,
        error: 0,
        blackberryTimeoutId : -1
    };

function handleBlackBerryLocationTimeout()
{
	if(bb.blackberryTimeoutId!=-1) {
		bb.error({ message:     "Timeout error", 
                   code:        3
               });
	}
}
function handleBlackBerryLocation()
{
		clearTimeout(bb.blackberryTimeoutId);
		bb.blackberryTimeoutId=-1;
        if (bb.success && bb.error) {
                if(blackberry.location.latitude==0 && blackberry.location.longitude==0) {
                        //http://dev.w3.org/geo/api/spec-source.html#position_unavailable_error
                        //POSITION_UNAVAILABLE (numeric value 2)
                        bb.error({message:"Position unavailable", code:2});
                }
                else
                {  
                        var timestamp=null;
                        //only available with 4.6 and later
                        //http://na.blackberry.com/eng/deliverables/8861/blackberry_location_568404_11.jsp
                        if (blackberry.location.timestamp)
                        {
                                timestamp = new Date( blackberry.location.timestamp );
                        }
                        bb.success( { timestamp:    timestamp , 
                                      coords: { 
                                            latitude:  blackberry.location.latitude,
                                            longitude: blackberry.location.longitude
                                        }
                                    });
                }
                //since blackberry.location.removeLocationUpdate();
                //is not working as described http://na.blackberry.com/eng/deliverables/8861/blackberry_location_removeLocationUpdate_568409_11.jsp
                //the callback are set to null to indicate that the job is done

                bb.success = null;
                bb.error = null;
        }
}

var geoPosition=function() {

        var pub = {};
        var provider=null;
		var u="undefined";
        var ipGeolocationSrv = 'http://freegeoip.net/json/?callback=JSONPCallback';

        pub.getCurrentPosition = function(success,error,opts)
        {
                provider.getCurrentPosition(success, error,opts);
        }

        pub.jsonp = {
            callbackCounter: 0,

            fetch: function(url, callback) {
                var fn = 'JSONPCallback_' + this.callbackCounter++;
                window[fn] = this.evalJSONP(callback);
                url = url.replace('=JSONPCallback', '=' + fn);

                var scriptTag = document.createElement('SCRIPT');
                scriptTag.src = url;
                document.getElementsByTagName('HEAD')[0].appendChild(scriptTag);
            },

            evalJSONP: function(callback) {
                return function(data) {
                    callback(data);
                }
            }
        }
		        

        pub.init = function()
        {			
                try
                {
                    //console.debug(( typeof(geoPositionSimulator)!=u ) && (geoPositionSimulator.length > 0 ) );
                    if ( ( typeof(geoPositionSimulator)!=u ) && (geoPositionSimulator.length > 0 ) ){
                            provider=geoPositionSimulator;
                    } else if (typeof(bondi)!=u && typeof(bondi.geolocation)!=u  ) {
                            provider=bondi.geolocation;
                    } else if (typeof(navigator.geolocation)!=u) {
                            provider=navigator.geolocation;
                            pub.getCurrentPosition = function(success, error, opts) {
                                    function _success(p) {
                                            //for mozilla geode,it returns the coordinates slightly differently
                                            var params;
                                            if(typeof(p.latitude)!=u) {
                                                    params = {
                                                        timestamp: p.timestamp, 
                                                        coords: {
                                                            latitude:  p.latitude,
                                                            longitude: p.longitude
                                                        }
                                                    };
                                            } else {
                                                    params = p;
                                            }
                                            success( params );
                                    }
                                    provider.getCurrentPosition(_success,error,opts);
                            }
                    } else if(typeof(window.blackberry)!=u && blackberry.location.GPSSupported) {
                            // set to autonomous mode
							if(typeof(blackberry.location.setAidMode)==u) {
                                return false;									
							}
							blackberry.location.setAidMode(2);
                            //override default method implementation
                            pub.getCurrentPosition = function(success,error,opts)
                            {
									//alert(parseFloat(navigator.appVersion));
                                    //passing over callbacks as parameter didn't work consistently
                                    //in the onLocationUpdate method, thats why they have to be set
                                    //outside
                                    bb.success = success;
                                    bb.error = error;
                                    //function needs to be a string according to
                                    //http://www.tonybunce.com/2008/05/08/Blackberry-Browser-Amp-GPS.aspx
									if(opts['timeout']) {
									 	bb.blackberryTimeoutId = setTimeout("handleBlackBerryLocationTimeout()",opts['timeout']);
									} else {
                                        //default timeout when none is given to prevent a hanging script
										bb.blackberryTimeoutId = setTimeout("handleBlackBerryLocationTimeout()",60000);
									}								
									blackberry.location.onLocationUpdate("handleBlackBerryLocation()");
                                    blackberry.location.refreshLocation();
                            }
                            provider = blackberry.location;				
                    
                    } else if ( typeof(Mojo) !=u && typeof(Mojo.Service.Request)!="Mojo.Service.Request") {
                            provider = true;
                            pub.getCurrentPosition = function(success, error, opts) {
                                parameters = {};
                                if( opts ) {
                                     //http://developer.palm.com/index.php?option=com_content&view=article&id=1673#GPS-getCurrentPosition
                                     if (opts.enableHighAccuracy && opts.enableHighAccuracy == true ){
                                            parameters.accuracy = 1;
                                     }
                                     if ( opts.maximumAge ) {
                                            parameters.maximumAge = opts.maximumAge;
                                     }
                                     if (opts.responseTime) {
                                            if( opts.responseTime < 5 ) {
                                                    parameters.responseTime = 1;
                                            } else if ( opts.responseTime < 20 ) {
                                                    parameters.responseTime = 2;
                                            } else {
                                                    parameters.timeout = 3;
                                            }
                                     }
                            }

                             r = new Mojo.Service.Request( 'palm://com.palm.location' , {
                                    method:"getCurrentPosition",
                                        parameters:parameters,
                                        onSuccess: function( p ){
                                            success( { timestamp: p.timestamp, 
                                                       coords: {
                                                            latitude:  p.latitude, 
                                                            longitude: p.longitude,
                                                            heading:   p.heading
                                                        }
                                                    });
                                        },
                                        onFailure: function( e ){
                                                            if (e.errorCode==1) {
                                                                error({ code:       3,
                                                                        message:    "Timeout"
                                                                    });
                                                            } else if (e.errorCode==2){
                                                                error({ code:       2,
                                                                        message:    "Position unavailable" 
                                                                    });
                                                            } else {
                                                                error({ code:       0,
                                                                        message:    "Unknown Error: webOS-code" + errorCode 
                                                                    });
                                                            }
                                                    }
                                        });
                            }

                    }
                    else if (typeof(device)!=u && typeof(device.getServiceObject)!=u) {
                            provider=device.getServiceObject("Service.Location", "ILocation");

                            //override default method implementation
                            pub.getCurrentPosition = function(success, error, opts){
                                    function callback(transId, eventCode, result) {
                                        if (eventCode == 4) {
                                            error({message:"Position unavailable", code:2});
                                        } else {
                                            //no timestamp of location given?
                                            success( {  timestamp:null, 
                                                        coords: {
                                                                latitude:   result.ReturnValue.Latitude, 
                                                                longitude:  result.ReturnValue.Longitude, 
                                                                altitude:   result.ReturnValue.Altitude,
                                                                heading:    result.ReturnValue.Heading }
                                                    });
                                        }
                                    }
                            //location criteria
                            
                            var criteria = new Object();
                            criteria.LocationInformationClass = "BasicLocationInformation";
                            //make the call
                            provider.ILocation.GetLocation(criteria,callback);
                            }
                    } else  {                            
                            pub.getCurrentPosition = function(success, error, opts) {
                                    pub.jsonp.fetch(ipGeolocationSrv, 
                                            function( p ){ success( { timestamp: p.timestamp, 
                                                                       coords: { 
                                                                            latitude:   p.latitude, 
                                                                            longitude:  p.longitude,
                                                                            heading:    p.heading
                                                                        }
                                                                    });});
                            }
                            provider = true;
                    }


                }
                catch (e){ 
					if( typeof(console) != u ) console.log(e);					
					return false;
				}
                return  provider!=null;
        }
        return pub;
}();

@@ functions.js
      var map, latLng, marker, infoWindow, ad;

      function initialize() {

        var myOptions = {
          zoom: 14,
          panControl: false, 
          streetViewControl: false, 
          scaleControl: false,
          scaleControlOptions: {position: google.maps.ControlPosition.BOTTOM_RIGHT},
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        map = new google.maps.Map(document.getElementById('googlemaps'), myOptions); 

	if (geoPosition.init()) 
	    geoPosition.getCurrentPosition(locationFound, defaultLocation, {enableHighAccuracy:true});
        else 
	    defaultLocation();

      }

      function defaultLocation() {
        showMap(38.8977, -77.0366);
      }

      function showMap(lat, lng) {

        latLng = new google.maps.LatLng(lat, lng);

        var adUnitDiv = document.createElement('div');

	var adWidth = window.innerWidth || document.documentElement.clientWidth;

	if ( adWidth >= 728 ) 
	  adFormat = google.maps.adsense.AdFormat.LEADERBOARD;
	else if ( adWidth >= 300 ) 
          adFormat = google.maps.adsense.AdFormat.SMALL_SQUARE; 
        else
          adFormat = google.maps.adsense.AdFormat.X_LARGE_VERTICAL_LINK_UNIT;      

        var adUnitOptions = {
          format: adFormat,
          position: google.maps.ControlPosition.BOTTOM,
          map: map,
          visible: false,
          publisherId: 'ca-pub-9238225005366006'
        }

//        ad = new google.maps.adsense.AdUnit(adUnitDiv, adUnitOptions);

        map.setCenter(latLng);

        marker = new google.maps.Marker({
           position: latLng, map: map, draggable: false, animation: google.maps.Animation.DROP
        });

        infoWindow = new google.maps.InfoWindow({
           content: '<div id="iw"><strong>Latitude ::</strong> ' + marker.getPosition().lat() + '<br/><strong>Longitude::</strong> ' + marker.getPosition().lng() + '</div>'
        });
	console.log(marker.getPosition().lat() + ',' + marker.getPosition().lng());
	//$.post('/email.cgi', {lat: marker.getPosition().lat(), lng: marker.getPosition().lng()});

        infoWindow.open(map, marker);

        google.maps.event.addListener(marker, 'dragstart', function (e) {
           infoWindow.close();
        });

        google.maps.event.addListener(marker, 'dragend', function (e) {
           var point = marker.getPosition();
           map.panTo(point);
           geocode(point);
        });

      }

      google.maps.event.addDomListener(window, 'load', initialize);
