#!/usr/bin/env perl
use Mojolicious::Lite;
use Digest::MD5 qw(md5_hex);
use Mojo::Redis2;
use Mojo::JSON 'j';

use Hash::Diff qw(left_diff);

plugin 'AssetPack';

app->secrets(['287328ye12ye1']);
app->asset('begl.js' => 'https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js', 'js/reconnecting-websocket.js', 'js/markerWithLabels.js');
app->asset('begl.css' => 'css/normalize.css', 'css/main.css');
app->sessions->default_expiration(86400*365*10);

#app->hook(after_dispatch => sub { 
#  my $c = shift; 
#$c->app->log->info($c->req->url->to_abs." ".$c->session('code'));
#  $c->res->headers->header('Access-Control-Allow-Origin' => '*'); 
#  $c->res->headers->header('Access-Control-Max-Age' => '0'); 
#  $c->res->headers->header('Access-Control-Allow-Credentials' => 'true'); 
#  $c->res->headers->header('Set-Cookie' => 'test=test'); 
#  $c->res->headers->header('Cache-Control' => 'no-cache'); 
#  $c->res->headers->header('Expires' => 'Fri, 01 Jan 1990 00:00:00 GMT'); 
#});

our $pals = {};

helper code => sub { substr(md5_hex(scalar localtime),int(rand(32-$_[1])),$_[1]) };
helper redis => sub { shift->stash->{redis} ||= Mojo::Redis2->new; };
helper pal_name => sub {
  my ($c, $pal, $ll) = @_;
  my $pals = $c->session('pals') || {};
  $ll = "$ll->[0],$ll->[1]";
  my $pal_name = $pals->{$pal} || $ll;
  warn "Pal ($ll): $pal_name" unless $pal_name eq $ll;
  return $ll => $pal_name;
};

if ( $ENV{REDIS_CLEAR} ) {
  app->log->info("Clearing redis");
  app->redis->del($_) foreach app->redis->keys("pals.*");
}

get '/' => sub {
  my $c = shift;
  my $length = 3;
  $c->session(code => $c->code(3)) unless $c->session('code');
  $c->render;
} => 'index';
get '/about';
get '/help';
get '/privacy';

post '/addpal' => sub {
  my $c = shift;
  my $code = $c->param('code') or return $c->reply->not_found;
  my $name = $c->param('name') or return $c->reply->not_found;
  my $pals = $c->session('pals');
  $pals->{$code} = $name || $code;
  $c->session({pals => $pals});
  $c->render(status => 200, text => '');
};

websocket '/pals' => => sub {
  my $c = shift;
  my $log = $c->app->log;
  my $code = $c->session('code') or return;
  my $redis = $c->redis;
  $c->on(connection => sub {
    $code or return;
  });
  $c->on(error => sub {
    $log->error("ERROR: $code");
  });
  $c->on(finish => sub {
    $code or return;
    delete $pals->{$code};
  });
  $c->on(message => sub {
    my ($c, $msg) = @_;
    return $c->send(1) if $msg eq '1';
    $code or return $c->send({json => {}});
    my ($lat, $lng) = split /,/, $msg;
    if( my $json = {lat => $lat, lng => $lng} ) {
      if ( ref $json eq 'HASH' ) {
        return $c->send({json => {}}) unless $json->{lat} && $json->{lng};
        $log->info("$code : $msg");
        $redis->setex("pals.$code" => 3*60 => j([$json->{lat}, $json->{lng}]));
      }
    }
    $pals->{$code}->{last} = $pals->{$code}->{this} if $pals->{$code}->{this};
    $pals->{$code}->{this} = {map { $c->pal_name($_ => j($redis->get("pals.$_"))) } grep { $_ ne $code } map { s/^pals\.//; $_ } @{$redis->keys('pals.*')}};
    my $diff = {
      beagles => $#{$redis->keys('pals.*')},
      add => left_diff(map { $pals->{$code}->{$_} } qw/this last/),
      del => left_diff(map { $pals->{$code}->{$_} } qw/last this/),
    };
    #warn Data::Dumper::Dumper($diff);
    $c->send({json => $diff});
  });
};

app->start;

__END__

=head1 COPYRIGHT AND LICENSE
Copyright (C) 2015, Stefan Adams.
This program is free software, you can redistribute it and/or modify it under
the terms of the Artistic License version 2.0.
=cut
